---
services:
  seadex-dev:
    build: .
    container_name: seadex-dev
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./db:/app/pb/pb_data
    ports:
      - 59991:59991
    restart: unless-stopped
